spring.application.name=chatLab
spring.datasource.url=jdbc:mysql://localhost:3306/chatlab?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Your Pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true